### ISSUE TITLE
Optional "Shape Name", for predictable behaviour when there are duplicate points

### ISSUE THREAD

**Issue by stuart321** [CorentinTh/quadtree-js#12]
If I have 2 or more points at identical x/y coordinates, e.g.
```
{x: 3, y:5}
{x: 3, y:5}
```
I believe some methods such as `remove` (and possibly others) don't support the scenario of removing a _specific_ point. One possible solution used by other libraries is allowing an optional "Shape Name" for uniqueness, and verifying this during removal, e.g.
```
{x: 3, y:5, shape_name: "Dog"}
{x: 3, y:5, shape_name: "Cat"}
```

then I guess in `removeRecursive` you'd have something like:
```
if (point.x === this.points[i].x && point.y === this.points[i].y && point.shape_name === this.points[i].shape_name) {
    this.points.splice(i, 1);
}
```

I was unsure if this would have repercussions for other methods too. Thanks for the great quadtree implementation.

**Comment by CorentinTh** [comment]
Hi @stuart321 
Thank you for those kind words and for your interrest in Quadtree.

You brought up a very important point that I never thought.
That's a good idea to add a custom field to check for uniqueness, and to not force everyone to implement unique names, and to allow more customisation, I'll maybe add a custom comparision function as a property in the configuration.

Something like this in your case:

```javascript
const config = {
    capacity: 10,            // default: 4
    removeEmptyNodes: true,  // default: false
    maximumDepth: 5,         // default: -1
    // default: (p1, p2) => p1.x === p2.x && p1.y === p2.y
    comparePoints: (p1, p2) => p1.x === p2.x && p1.y === p2.y && p1.name === p2.name
};

const quadtree = new QuadTree(boundingArea, config);
```
And `removeRecursive` would be like:
```javascript
if (this.config.comparePoints(point, this.points[i])) {
    this.points.splice(i, 1);
}
```

What do you think of this solution ?

**Comment by stuart321** [comment]
I like the custom comparison approach, makes it very versatile.

**Comment by CorentinTh** [comment]
Added `arePointsEqual` in the config.
