### ISSUE TITLE
Update tree

### ISSUE THREAD

**Issue by manix** [CorentinTh/quadtree-js#16]
What do I need to do after changing a point's coordinates so that the tree updates?

**Comment by CorentinTh** [comment]
Hi @manix 
Thank you for your interrest in my Quadtree.

If you change a point coordinates, the best way to update the Quadtree is to remove the point and reinsert it. If all you point may have changed, you can clear the quadtree and reinsert them. 

Removing and inserting point are rather cheap operations.
