### ISSUE TITLE
Why not use Math functions?

### ISSUE THREAD

**Issue by manix** [CorentinTh/quadtree-js#17]
Hello, I noticed something small that might have been overlooked.

https://github.com/CorentinTh/quadtree-js/blob/68e79e57e6c41e76e5734d10f4e64de52e7572cf/src/Circle.ts#L49-L55

Here `Math.min` and `Math.max` can be utilized instead of defining new functions on every call? 

I decided to ask if there is a reason for this?

**Comment by CorentinTh** [comment]
Hi!
Indeed, their is actually no reason for this. 
I did not thought of `Math.min`/`Math.max` the first time I build that 2 years ago.

That's a good point, thank you for noticicing, I'll refactor it to avoid those useless variables declaration.
