### ISSUE TITLE
Update the readme for search and box examples

### ISSUE THREAD

**Issue by amitrokade47** [CorentinTh/quadtree-js#19]
new Box(0, 0, 1000, 1000)
Could you specify in the readme that the parameter values are actually x0,y0,width,height for the box and search methods?
I spent a lot of time considering the values to be coordinates x0,y0,x2,y2.
It could help someone else who might accidentally assume the values like I `did.```

**Comment by CorentinTh** [comment]
Hi @amitrokade47 
Thank you for your interest in Quadtree.

That's a good point, I'll add some info about the bouding boxs in the readme.
