### ISSUE TITLE
Return boolean after insert

### ISSUE THREAD

**Issue by desoro** [CorentinTh/quadtree-js#23]
Is it possible to return a boolean after an insert that returns true/false depending on whether the insert failed because the capacity is reached? I could simply catch the error and consider that false, but that isn't very elegant - especially when using typescript.

**Comment by CorentinTh** [comment]
Hi!
You're making a good point, I've not thought of this.
And everything is kind of ready to make this work. 

I will implement it. 
But what could be the return value when inserting an array of point ?
 * True if everything has been inserted correctly, false otherwise ?
 * An array of true/false matching each point ?

**Comment by CorentinTh** [comment]
Btw, what is the error you're actually catching to check for insertion @desoro ?

**Comment by desoro** [comment]
I suggest "True if everything has been inserted correctly, false otherwise" for the array of points.

As for the error, when you try to insert past the capacity, the insertRecursive function throws an error of "RangeError: Maximum call stack exceeded". This was with the default capacity of 4 and unlimited depth (-1).

**Comment by CorentinTh** [comment]
It should not be a problem for this use case, if you get a maximum call stack during insertion it's probably due to points with the same coordinates. I suggest setting a max depth for the tree (see related issue #5).

Yet, I'll implement the boolean for insertion

**Comment by desoro** [comment]
Ahh, it would appear so. If I ensure the points are unique, it just silently fails. I am using the quadtree for interest management in a 2d game, so player positions will overlap uncontrollably. How would you suggest I handle this? Will setting a max depth really hurt that much for my use case?

**Comment by CorentinTh** [comment]
Setting a maximum depth may not impact your performance, depending on the amount of points in your game, and whereas your points are globally stacked on the same spot on the map.

**Comment by CorentinTh** [comment]
I'm closing the issue, don't hesitate if you still have questions
