### ISSUE TITLE
[BUG] .insert method not working

### ISSUE THREAD

**Issue by gurkansahinn** [CorentinTh/quadtree-js#81]
**Describe your environement**
* **Environement**: node 
* **Node version** (if applicable): v17.0.1
* **Browser** (if applicable): not browser

**Describe the bug**
when i try to .insert quadtree after a while it doesn't work

**To Reproduce**
1. Create quadtree
2. Wait like 1-2 minutes
3. try .insert method with any data

**Expected behavior**
.p

**Code examples**
```javascript
public static globalQuadTree: tree.QuadTree = new tree.QuadTree(new tree.Box(0, 0, 1000, 1000));

ObjectService.globalQuadTree.insert(new tree.Point(this.position.x, this.position.y, this));
console.log(ObjectService.globalQuadTree.getAllPoints());
```

**Additional context**
-

**Comment by CorentinTh** [comment]
Hello !
Thanks for the bug report, I'll investigate today 🙏🏻

**Comment by CorentinTh** [comment]
So I tested to insert a point in the quadtree after 2 min and it worked fine
My test script : 

```javascript
// index.js
const { QuadTree, Box, Point, Circle } = require('js-quadtree');
const { version } = process;

const quadtree = new QuadTree(new Box(0, 0, 1000, 1000));
quadtree.insert(new Point(100, 200, 1));

setTimeout(() => {
    quadtree.insert(new Point(200, 100, 2));

    const results = quadtree.query(new Circle(150, 150, 100));

    console.log({ results, version });
}, 1000 * 60 * 2) // 2 minutes
``` 

```shell
$ node index.js 
{
  results: [ { x: 100, y: 200, data: 1 }, { x: 200, y: 100, data: 2 } ],
  version: 'v17.0.1'
}
```

So the possible problems : 
* my test example is not in the condition as yours
* you try to insert a point outside of the quadtree range 

So please provide a minimal reproducible example if you want me to investigate more about this issue

**Comment by gurkansahinn** [comment]
I was trying to implement BOX in a game and it only works at zero point. My fault.
